### ISSUE TITLE
TUIOListener Unity Integration

### ISSUE THREAD

**Issue by justinLifelike** [gregharding/TUIOListener#1]
Hi I want to import or make a TUIOListener into my unity project but can't seem to find how.
Could you help me start please? 

Thanks in advance

**Comment by gregharding** [comment]
hi Justin, it looks like you've already found [https://github.com/gregharding/TUIOSimulator](https://github.com/gregharding/TUIOSimulator). This TUIOListener project is only intended as a command line listener/debugger.
